name            'eliasp-mascot'
version         '0.0.1'
source          'http://github.com/eliasp/puppet-mascot.git'
author          'eliasp'
license         'Apache License, Version 2.0'
summary         'Setup/configure the MatrixScience Mascot Server'
description     'Setup and configure the MatrixScience Mascot Server as far as possible using Puppet'
project_page    'http://github.com/eliasp/puppet-mascot'
